# Generated by Django 2.1.7 on 2019-03-06 08:05

import django.core.validators
from django.db import migrations, models
import swe0.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=swe0.profiles.models._generate_picture_filename, validators=[django.core.validators.FileExtensionValidator(['gif', 'jpeg', 'jpg', 'png', 'svg'])]),
        ),
    ]
