# Generated by Django 2.1.5 on 2019-01-30 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190130_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name': 'check-in'},
        ),
        migrations.AddField(
            model_name='checkin',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='check_in_code',
            field=models.CharField(blank=True, help_text='If empty, a code will automatically be generated.', max_length=25, unique=True),
        ),
    ]
