# Generated by Django 2.1.5 on 2019-02-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190222_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start_time', '-end_time', 'title')},
        ),
    ]
